### ISSUE TITLE
Support question: possible for async controls with twing?

### ISSUE THREAD

**Issue by tjheffner** [MichaelAllenWarner/dte-storybook#2]
Hello again 😅 

I'm working on setting storybook up with twig support. This repo (and your help earlier with the drupal-attribute!) have been invaluable.

I bumped into one last problem, and surprise surprise, I found you in the Storybook issue queue here: https://github.com/storybookjs/storybook/issues/16260

Curious if the PR mentioned in that issue fixed the problem you were having, or if you found some other way to hook Storybook Controls to the html resolved in the Twing promise.

I've forked this repo here: https://github.com/tjheffner/dte-storybook and added some basic control handling (auto-generated from `npx sb init -t html` in my original case). When I add console.log()'s to the global loader

```js
export const loaders = [
  async ({ args, originalStoryFn }) => {
    if (originalStoryFn.render) {
      console.log(args)
      const renderedStory = await originalStoryFn.render(args);
      console.log(renderedStory);
      return { renderedStory };
    }
  },
];
```

I can clearly see the loader being called again when the controls update, but the renderedStory never updates. 
<img width="972" alt="Screen Shot 2022-03-16 at 2 11 41 PM" src="https://user-images.githubusercontent.com/11279744/158691790-42253edc-adf0-4f12-9708-d0f58f44c1e8.png">

Any pointers or tips would be greatly appreciated

**Comment by MichaelAllenWarner** [comment]
Yes, the issue was resolved for me after that PR, but also, that `dte-storybook` repo isn't exactly what I'm running; I've moved to [CSF 3.0](https://storybook.js.org/blog/component-story-format-3-0/), so maybe that's the difference?

If you want to try my CSF 3.0 setup, I think you need to add this to your `main.js` export-object:

```js
features: {
  storyStoreV7: true,
},

framework: '@storybook/html',
```

Then change your global loader in `preview.js` to:

```js
export const loaders = [
  async ({
    args,
    parameters,
  }) => {
    const renderedStory = await parameters.render(args);
    return { renderedStory };
  },
];
```

And add a global-render function to `preview.js`:

```js
export const render = (_, { loaded: { renderedStory } }) => renderedStory;
```

And finally, change `Example.render` in your stories to `Example.parameters.render`.

(Sorry if any of that isn't quite right; working quickly and removing all my TypeScript annotations.)

**Comment by MichaelAllenWarner** [comment]
(Oh, and follow the instructions at the CSF 3.0 link for refactoring stories as objects instead of functions.)

**Comment by tjheffner** [comment]
I appreciate the prompt response! I found another way to make it work, practically seconds after you responded 😅 

In the actual `*.stories.js` I need to provide the control args as well. A brainfart moment, really.

```
Block.render = async args => {
  return await block({
    ...Block.args, ...args
  })
}
```

Spreading in the async args is the glue for storybook controls. Thanks again for all of your help!
